version: '3'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-pro:latest
    volumes:
    - /tmp/opt/jfrog/artifactory:/var/opt/jfrog/artifactory
    - ./plugins:/var/opt/jfrog/artifactory/etc/plugins
    - ./properties/artifactory.system.properties:/var/opt/jfrog/artifactory/etc/artifactory.system.properties
    ports:
    - "8081:8081"
  
  rp:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/artifactory.conf:ro
    ports:
    - "80:80"
    depends_on:
    - artifactory